# Generated by Django 4.0.5 on 2022-06-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del Proyecto')),
                ('descrip', models.TextField(max_length=250, verbose_name='Descripción del Proyecto')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duración del Proyect')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('activo', models.BooleanField(default=False)),

            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
            },
        ),
    ]
