# Generated by Django 4.0.6 on 2022-07-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_proyecto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='proyecto/'),
        ),
    ]
