# Generated by Django 4.0.6 on 2022-07-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_proyecto_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre del Proyecto'),
        ),
    ]
