# Generated by Django 4.0.6 on 2022-07-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaProyecto',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.proyecto')),
                ('nombre_programa', models.CharField(max_length=250, verbose_name='Nombre del Programa')),
                ('nombre_proyecto', models.TextField(max_length=250, verbose_name='Nombre del proyecto')),
                ('codigo_proyecto', models.TextField(max_length=250, verbose_name='Código del proyecto')),
                ('clasificacion_proyecto', models.TextField(max_length=250, verbose_name='Clasificación del proyecto')),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='duracion',
        ),
    ]
