# Generated by Django 4.1.1 on 2022-09-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_servicios_alter_proyecto_file_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
